### ISSUE TITLE
Chokes on GeoJSON files as UTF with BOM 

### ISSUE THREAD

**Issue by pauldzy** [mapbox/geojson-rewind#17]
I am strangely finding certain Esri products of late outputting GeoJSON as UTF with a byte order mark.  I noticed your rewind code crashes on these files.

Cheers,
Paul

[bom_example.json.txt](https://github.com/mapbox/geojson-rewind/files/1653381/bom_example.json.txt)

**Comment by mourner** [comment]
I'm inclined to close this because JSON with a BOM is invalid [according to the spec](https://tools.ietf.org/html/rfc7159#section-8.1):

> Implementations MUST NOT add a byte order mark to the beginning of a JSON text.

It's best to strip out BOM using [some other CLI tool](https://stackoverflow.com/questions/45240387/how-can-i-remove-the-bom-from-a-utf-8-file) prior to feeding it to any JSON-handling tools.
